"""
Tithi Enumeration

Defines all 30 lunar tithis.
"""

from enum import Enum


class Tithi(Enum):

    SHUKLA_PRATIPADA = 1
    SHUKLA_DVITIYA = 2
    SHUKLA_TRITIYA = 3
    SHUKLA_CHATURTHI = 4
    SHUKLA_PANCHAMI = 5
    SHUKLA_SHASHTHI = 6
    SHUKLA_SAPTAMI = 7
    SHUKLA_ASHTAMI = 8
    SHUKLA_NAVAMI = 9
    SHUKLA_DASHAMI = 10
    SHUKLA_EKADASHI = 11
    SHUKLA_DVADASHI = 12
    SHUKLA_TRAYODASHI = 13
    SHUKLA_CHATURDASHI = 14
    PURNIMA = 15

    KRISHNA_PRATIPADA = 16
    KRISHNA_DVITIYA = 17
    KRISHNA_TRITIYA = 18
    KRISHNA_CHATURTHI = 19
    KRISHNA_PANCHAMI = 20
    KRISHNA_SHASHTHI = 21
    KRISHNA_SAPTAMI = 22
    KRISHNA_ASHTAMI = 23
    KRISHNA_NAVAMI = 24
    KRISHNA_DASHAMI = 25
    KRISHNA_EKADASHI = 26
    KRISHNA_DVADASHI = 27
    KRISHNA_TRAYODASHI = 28
    KRISHNA_CHATURDASHI = 29
    AMAVASYA = 30